name: main-merged
on:
  push:
    branches:
      - main
      - feature/github-actions
env:
  SHARED_ACCOUNT: 851725521087
  DEV_ACCOUNT: "058264110781"
  REGION: us-east-1
  HUSKY: 0
  CI: 'true'
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}